name: cron-artifact-cleanup
# This is a basic workflow to help you get started with Actionsname: nightly-cleanup# Controls when the workflow will run
on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
jobs:
# This workflow contains a single job called "build"
  build:
# The type of runner that the job will run on
    runs-on: ubuntu-latest# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
# Runs a set of commands using the runners shell
      - name: Delete all artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.G_TOKEN }}
          expire-in: 0days # Setting this to 0 will delete all artifacts
